language: "English"
time:
  hour: 18
  minute: 12
  second: 36
repository:
  directory: "-path /home/svyatoslav/goProjects/src/github.com/Slava12/Go_Project_1/configuration.yaml"
  file: "testProgram.go"
system:
  name: "Linux Mint"
  release: "18.2"
  codename: "Sonya"